#Config for lottery Plugin

#DO NOT TOUCH 
config-version: 2

#Maximum count of items you can win
max-price: 10

#message
Message:
#allowed replacement-tags: none            
  deny: You already had your lottery.
  
#allowed replacement-tags: %AMOUNT% %WONITEM 
  allow: You get %AMOUNT% of %WONITEM%.
  
#allowed replacement-tags: %PAYITEM%
  noitem: You have no more %PAYITEM%.
  
#allowed replacement-tags: %PLAYER% %AMOUNT% %WONITEM%
  broadcast: Gratz! %PLAYER% won %AMOUNT% of %WONITEM%.
  

#Name of the Item that is used to pay
#WARNING: Item ID's wont work!
itemtopay: GOLD_INGOT

#amount to pay
amounttopay: 1

#You can chose if you want to use the blacklist, or the whitelist
#whitelist means it will only use the items that are written into the whitelist.yml file.
#blacklist means it will not use the items written into the blacklist.yml file.
#itemlist: [blacklist/whitelist]
itemlist: blacklist

#Broadcast when someone win's an item
do-broadcast: true