#Config for lottery Plugin

#DO NOT TOUCH 
config-version: 1

#Maximum count of items you can win
max-price: 10

#message
Message:
  deny: Du hattest heute schon Lotterie.
  allow: Du bekommst 
  noitem:
    1: Du hast kein 
    2: mehr
  broadcast: gewinnt

#Itemid of the Item that is used to pay
itemtopay: 266

#amount to pay
amounttopay: 1

#itemblacklist with bedrock as example
itemblacklist:
  - 7

#do a broadcast if someone is playing the game
do-broadcast: true