#Config for lottery Plugin

#DO NOT TOUCH 
config-version: 1

#Maximum count of items you can win
max-price: 10

#message
Message:
  deny: You already had your lottery.
  allow: You get %AMOUNT% of %WONITEM%.
  noitem: You have no more %PAYITEM%.
  broadcast: Gratz! %PLAYER% won %AMOUNT% of %WONITEM%.

#Itemid of the Item that is used to pay
itemtopay: 266

#amount to pay
amounttopay: 1

#itemblacklist with bedrock as example
itemblacklist:
  - 7

#do a broadcast if someone is playing the game
do-broadcast: true