#Config for MinecraftLottery Plugin

#DO NOT TOUCH 
config-version: 4
database-version: 2

#Set to false if you don't want to let the plugin check for updates.
checkforupdate: true

#Distance in minutes between lottery
#set to 0 to allow the user to do as many lottery's as he wants.
#HOUR: 60 min, DAY: 1440 min
distance: 1440 #Minutes 

#Maximum count of items you can win
max-price: 10

#message
Message:
#Message when the player tries to         
  deny: You already had your lottery.
  
#Message that the player gets that does the lottery
  allow: You get %AMOUNT% of %WONITEM%.
  
#message when the player has no item to pay.
  noitem: You have no %PAYITEM% in your inventory.
  
#Broadcast that will be send when the player won an item.
  broadcast: Gratz! %PLAYER% won %AMOUNT% of %WONITEM%.
  
#Message when the player needs more space in the inventory.  
  morespace: You need more space in your inventory.

#Name of the Item that is used to pay
#WARNING: Item ID's wont work!
itemtopay: GOLD_INGOT

#amount to pay
amounttopay: 1

#You can chose if you want to use the blacklist, or the whitelist
#whitelist means it will only use the items that are written into the whitelist.yml file.
#blacklist means it will not use the items written into the blacklist.yml file.
#itemlist: [blacklist/whitelist]
itemlist: blacklist

#Broadcast when someone win's an item
do-broadcast: true


