name: MinecraftLottery
version: 1.1
main: me.darcade.minecraftlottery.MinecraftLottery
author: Darcade, Natenom
website: http://darcade.de/, http://natenom.name/
commands:
     lottery:
          description: Gives the player executing the command a random item.
          usage: /<command>
          permission: lottery