name: MinecraftLottery
version: 1.1
main: me.darcade.minecraftlottery.MinecraftLottery
author: Darcade, Natenom
website: http://darcade.de/, http://natenom.name/
commands:
     lottery:
          description: Gives the player executing the command a random item. Admins can execute the lottery for other players by typing /lottery USERNAME [force]
          usage: /<command> [USERNAME [force]]
          permission: minecraftlottery 