name: lottery
version: 1.0
main: me.darcade.lottery.lottery
author: Darcade, Natenom
website: http://darcade.de/, http://natenom.name/
commands:
     lottery:
          description: does the lottery
          usage: /<command>
          permission: lottery