name: lottery
version: 0.1
main: me.darcade.lottery.lottery
author: Darcade
website: http://darcade.de/
commands:
     lottery:
          description: IM MOMENT SINNLOS
          usage: /<command>
permissions:
    lottery:
        description: Allows player to do the lottery